project_id = "gxqrmxhpltfkkhhtqvmh"

[functions.generate-pdf]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.check-notifications]
verify_jwt = false

[functions.preview-transactional-email]
verify_jwt = false

[functions.export-proposals-leads]
verify_jwt = false

[functions.send-bulk-email]
verify_jwt = false

[functions.ingest-lead]
verify_jwt = false

[functions.send-whatsapp-gptmaker]
verify_jwt = false

[functions.enrich-lead]
verify_jwt = false

[functions.send-call-scheduled-alert]
verify_jwt = false

[functions.handle-email-events]
verify_jwt = false
